name: Payslip Processor

on:
  push:
    paths:
      - "payslips/*.pdf"

jobs:
  run-script:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python extract.py
      
      - name: Delete processed payslip
        run: rm -f payslips/*.pdf
        
      - name: Commit updates
        run: |
          git config --global user.name "automation"
          git config --global user.email "bot@github.com"
          git add -A

          git diff --staged --quiet || git commit -m "Update finance data"

          git push
